<?php

namespace App\Http\Controllers\Documents;

use App\Http\Controllers\Controller;
use App\Models\EmployeeDocument;
use App\Models\EmployeeDocumentHistory;
use App\Models\EmployeeRequestDetail;
use App\Models\SalesCrm\Employee;
use Carbon\Carbon;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Inertia\Inertia;
use Inertia\Response;

class LetterRequestController extends Controller
{
    public function index(Request $request): Response
    {
        $query = EmployeeDocument::query()
            ->with([
                'documentType',
                'documentTemplate',
                'requestDetails',
            ])
            ->whereHas('documentType.category', function ($q) {
                $q->where('short_code', 'letter_requests');
            });

        if ($request->filled('status')) {
            $query->where('status', $request->input('status'));
        }

        if ($request->filled('search')) {
            $search = $request->input('search');
            $query->where(function ($q) use ($search) {
                $q->where('document_title', 'like', "%{$search}%")
                    ->orWhereHas('documentType', function ($sub) use ($search) {
                        $sub->where('document_name', 'like', "%{$search}%");
                    });
            });
        }

        $requests = $query->orderByDesc('id')
            ->paginate(15)
            ->withQueryString()
            ->through(fn (EmployeeDocument $doc) => $this->payload($doc));

        return Inertia::render('letter-requests/index', [
            'requests' => $requests,
            'filters' => $request->only(['status', 'search']),
        ]);
    }

    public function show(EmployeeDocument $letterRequest): Response
    {
        $letterRequest->load([
            'documentType',
            'documentTemplate',
            'requestDetails',
            'histories' => fn ($q) => $q->orderByDesc('id'),
        ]);

        $employee = Employee::query()->with('user:id,name,email', 'department:id,name', 'organisation:id,name')->find($letterRequest->employee_id);

        return Inertia::render('letter-requests/show', [
            'request' => $this->payload($letterRequest),
            'employee' => $employee,
        ]);
    }

    public function approve(Request $request, EmployeeDocument $letterRequest): RedirectResponse
    {
        $request->validate([
            'salary_amount' => 'nullable|string|max:50',
            'bank_iban' => 'nullable|string|max:100',
            'remarks' => 'nullable|string|max:500',
        ]);

        DB::transaction(function () use ($request, $letterRequest) {
            $letterRequest->update([
                'status' => 'approved',
                'remarks' => $request->input('remarks'),
            ]);

            if ($request->filled('salary_amount')) {
                EmployeeRequestDetail::query()->updateOrCreate(
                    ['employee_document_id' => $letterRequest->id, 'field_key' => 'salary_amount'],
                    ['field_name' => 'Approved Salary', 'field_value' => $request->input('salary_amount')]
                );
            }

            if ($request->filled('bank_iban')) {
                EmployeeRequestDetail::query()->updateOrCreate(
                    ['employee_document_id' => $letterRequest->id, 'field_key' => 'bank_iban'],
                    ['field_name' => 'Bank IBAN', 'field_value' => $request->input('bank_iban')]
                );
            }

            EmployeeDocumentHistory::query()->create([
                'employee_document_id' => $letterRequest->id,
                'action_type' => 'approved',
                'remarks' => $request->input('remarks', 'Letter approved and generated by HR'),
                'done_by' => $request->user()?->id,
                'action_on' => Carbon::now(),
            ]);
        });

        return back()->with('toast', ['type' => 'success', 'message' => 'Letter request approved successfully.']);
    }

    public function reject(Request $request, EmployeeDocument $letterRequest): RedirectResponse
    {
        $request->validate([
            'remarks' => 'required|string|max:500',
        ]);

        $letterRequest->update([
            'status' => 'rejected',
            'remarks' => $request->input('remarks'),
        ]);

        EmployeeDocumentHistory::query()->create([
            'employee_document_id' => $letterRequest->id,
            'action_type' => 'rejected',
            'remarks' => $request->input('remarks'),
            'done_by' => $request->user()?->id,
            'action_on' => Carbon::now(),
        ]);

        return back()->with('toast', ['type' => 'success', 'message' => 'Letter request rejected.']);
    }

    protected function renderDocumentHtml(EmployeeDocument $doc, ?Employee $employee): ?string
    {
        $template = $doc->documentTemplate
            ?? $doc->documentType?->documentTemplates()->where('status', 1)->first();

        if (! $template || empty($template->template_code)) {
            return null;
        }

        $details = $doc->requestDetails->pluck('field_value', 'field_key')->all();
        $employee?->loadMissing(['user', 'department', 'organisation']);
        $profile = $employee?->profile();

        $replacements = [
            '{{company_name}}' => $employee?->organisation?->org_name ?? config('app.name', 'HRMS'),
            '{{company_address}}' => 'Dubai, United Arab Emirates',
            '{{company_phone}}' => '+971 4 000 0000',
            '{{company_email}}' => 'hr@company.com',
            '{{employee_name}}' => $employee?->user?->name ?? "Employee #{$doc->employee_id}",
            '{{employee_code}}' => $employee?->emp_num ?? "EMP-{$doc->employee_id}",
            '{{passport_number}}' => '—',
            '{{emirates_id}}' => '—',
            '{{designation}}' => $details['visa_designation'] ?? ($employee?->designation ?? 'Employee'),
            '{{department}}' => $employee?->department?->name ?? 'General',
            '{{joining_date}}' => $employee?->joining_date ? Carbon::parse($employee->joining_date)->format('d M Y') : '—',
            '{{basic_salary}}' => $employee?->basic_salary ? number_format((float) $employee->basic_salary, 2) : '0.00',
            '{{housing_allowance}}' => $employee?->housing_allowance ? number_format((float) $employee->housing_allowance, 2) : '0.00',
            '{{other_allowance}}' => '0.00',
            '{{gross_salary}}' => $employee?->gross_salary ? number_format((float) $employee->gross_salary, 2) : '0.00',
            '{{document_number}}' => $doc->document_number ?: ('DOC-'.str_pad((string) $doc->id, 5, '0', STR_PAD_LEFT)),
            '{{issue_date}}' => $doc->issue_date ? $doc->issue_date->format('d M Y') : Carbon::now()->format('d M Y'),
            '{{purpose}}' => $details['purpose'] ?? 'Official Purpose',
            '{{to_address}}' => $details['to_address'] ?? 'To Whom It May Concern',
            '{{visa_designation}}' => $details['visa_designation'] ?? ($employee?->designation ?? 'Employee'),
            '{{payroll_month}}' => Carbon::now()->format('F Y'),
            '{{net_salary}}' => $employee?->gross_salary ? number_format((float) $employee->gross_salary, 2) : '0.00',
            '{{gross_earnings}}' => $employee?->gross_salary ? number_format((float) $employee->gross_salary, 2) : '0.00',
            '{{deductions_unpaid}}' => '0.00',
            '{{deductions_other}}' => '0.00',
            '{{total_deductions}}' => '0.00',
            '{{transport_allowance}}' => '0.00',
            '{{bank_account_masked}}' => '•••• •••• •••• 1234',
            '{{bank_name}}' => 'Emirates NBD',
            '{{account_number}}' => '1234567890',
            '{{iban_number}}' => 'AE000000000000000000000',
        ];

        foreach ($details as $k => $v) {
            $replacements['{{'.$k.'}}'] = (string) $v;
        }

        return str_replace(array_keys($replacements), array_values($replacements), $template->template_code);
    }

    protected function payload(EmployeeDocument $doc): array
    {
        $employee = Employee::query()->with(['user:id,name,email', 'department:id,name', 'organisation'])->find($doc->employee_id);
        $details = $doc->requestDetails->pluck('field_value', 'field_key');

        return [
            'id' => $doc->id,
            'employee_id' => $doc->employee_id,
            'employee_name' => $employee?->user?->name ?? "Employee #{$doc->employee_id}",
            'employee_email' => $employee?->user?->email,
            'emp_num' => $employee?->emp_num,
            'document_name' => $doc->documentType?->document_name,
            'document_code' => $doc->documentType?->document_code,
            'purpose' => $details['purpose'] ?? 'General Request',
            'details' => $details['details'] ?? $doc->remarks,
            'to_address' => $details['to_address'] ?? null,
            'visa_designation' => $details['visa_designation'] ?? null,
            'salary_amount' => $details['salary_amount'] ?? null,
            'bank_iban' => $details['bank_iban'] ?? null,
            'status' => $doc->status,
            'remarks' => $doc->remarks,
            'applied_date' => $doc->created_at?->format('d M Y'),
            'approved_date' => $doc->status === 'approved' ? $doc->updated_at?->format('d M Y') : null,
            'rendered_html' => $this->renderDocumentHtml($doc, $employee),
            'histories' => $doc->histories->map(fn ($h) => [
                'id' => $h->id,
                'action_type' => $h->action_type,
                'remarks' => $h->remarks,
                'action_on' => $h->action_on?->format('d M Y H:i'),
            ]),
        ];
    }
}
